# 指定Master仓库和阿里云仓库
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!  #pod工程中不显示警告
target 'XMusicPlayerDemo' do
    pod 'DOUAudioStreamer'
    pod 'AFNetworking'
    pod 'SDWebImage', '~> 3.8.2'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'YYModel'
end
